linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/transcom/mymove

linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
  disable:
    - gosimple #deprecated https://github.com/golangci/golangci-lint/issues/357
    - unused #deprecated https://github.com/dominikh/go-tools/tree/master/cmd/unused
  fast: false

issues:
  exclude-rules:
    # skip analyzing dutystationsloader until repeated tags from embedded types are fixed https://github.com/golang/go/issues/30846
    - path: internal/pkg/dutystationsloader/duty_stations_loader.go
      linters:
        - govet
  fix: true

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 8m
  concurrency: 1
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - pkg/assets
    - pkg/gen
    - mocks
  skip-dirs-use-default: true
  modules-download-mode: readonly
