FROM alpine:3.12.3

COPY bin/orders-api-client /bin/orders-api-client

# Install data needed for tests
COPY config/tls/ /bin/config/tls/
COPY testdata/ /bin/testdata/

# Install tools needed in container
RUN apk update
RUN apk add postgresql-client bash --no-cache

WORKDIR /bin
