# Local Development environment
FROM milmove/circleci-docker:milmove-orders
# Base image uses "circleci", to avoid using `sudo` run as root user
USER root

ENV PATH="/app/bin:/app/scripts:${PATH}"

USER circleci
