version: '3.3'

#
# Used for devlopment inside docker, mounting project directory and running psql
#

services:
  database:
    image: postgres:10.10
    restart: always
    ports:
      - '7432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=dev_db

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - database
    ports:
      - '7001:7001'
      - '7080:7080'
      - '6443:6443'
      - '7443:7443'
    environment:
      - APPLICATION=orders
      - AWS_ACCESS_KEY_ID
      - AWS_ACCOUNT_ID
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_REGION
      - AWS_SDK_LOAD_CONFIG
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_EXPIRATION
      - AWS_SESSION_TOKEN
      - CHAMBER_RETRIES=20
      - DB_DEBUG=1
      - DB_ENV=development
      - DB_HOST=database
      - DB_NAME=dev_db
      - DB_NAME_DEPLOYED_MIGRATIONS=deployed_migrations
      - DB_NAME_DEV=dev_db
      - DB_NAME_TEST=test_db
      - DB_PASSWORD=mysecretpassword
      - DB_PORT=5432
      - DB_REGION=us-west-2
      - DB_RETRY_INTERVAL=5s
      - DB_SSL_MODE=disable
      - DB_USER=postgres
      - DEVLOCAL_CA=/home/circleci/milmove_orders/config/tls/devlocal-ca.pem
      - DOD_CA_PACKAGE=/home/circleci/milmove_orders/config/tls/Certificates_PKCS7_v5.6_DoD.der.p7b
      - ENVIRONMENT=development
      - GIN_PORT=7001
      - GO111MODULE=auto
      - GOLANGCI_LINT_CONCURRENCY=6
      - GOLANGCI_LINT_VERBOSE=
      - HTTP_ORDERS_SERVER_NAME=orderslocal
      - IWS_RBS_ENABLED=0
      - IWS_RBS_HOST=pkict.dmdc.osd.mil
      - MIGRATION_MANIFEST=/home/circleci/milmove_orders/migrations/orders/migrations_manifest.txt
      - MIGRATION_PATH=file:///home/circleci/milmove_orders/migrations/orders/schema;file:///home/circleci/milmove_orders/migrations/orders/secure
      - MOVE_MIL_DOD_CA_CERT
      - MOVE_MIL_DOD_TLS_CERT
      - MOVE_MIL_DOD_TLS_KEY
      - MUTUAL_TLS_ENABLED=1
      - MUTUAL_TLS_PORT=7443
      - NO_TLS_ENABLED=0
      - NO_TLS_PORT=7080
      - PGPASSWORD=mysecretpassword
      - SERVE_ORDERS=true
      - TLS_ENABLED=0
      - TLS_PORT=6443
      - TZ=UTC
    volumes:
      - ./:/home/circleci/milmove_orders
    working_dir: /home/circleci/milmove_orders
