# Settings found in https://dependabot.com/docs/config-file/
version: 1
update_configs:

  # Keep go.mod (& go.sum) up to date daily
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    default_labels:
      - dependencies
      - automerge

  # Keep Dockerfile up to date, batching pull requests daily
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    default_labels:
      - dependencies
      - automerge
