#! /usr/bin/env bash

#
# Announce broken deploy steps on master branch to Pager Duty
#

set -euo pipefail

#####
## Exit and do nothing else unless this is the 'master' branch
[[ $CIRCLE_BRANCH = master ]] || exit 0

#####
## Exit and do nothing else unless a deploy job
#####
[[ $CIRCLE_JOB = *"deploy"* ]] || exit 0

#####
## Page the on-call via PagerDuty
#####

NOW_ISO8601=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

pretext="CircleCI $CIRCLE_BRANCH branch failure!"
title="CircleCI build #$CIRCLE_BUILD_NUM failed on job $CIRCLE_JOB"
message="The $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH branch broke on job $CIRCLE_JOB! Contact $CIRCLE_USERNAME for more information."

pd_payload=$(
cat <<EOM
{
  "payload": {
    "summary": "$message",
    "timestamp": "$NOW_ISO8601",
    "source": "$pretext $title",
    "severity": "info",
    "class": "cicd failure"
  },
  "routing_key": "$PD_ROUTING_KEY",
  "dedup_key": "circle-$CIRCLE_WORKFLOW_ID",
  "links": [{
    "href": "$CIRCLE_BUILD_URL",
    "text": "CircleCI Build URL"
  }],
  "event_action": "trigger"
}
EOM
)

echo
echo "Pager Duty Payload:"
echo "$pd_payload"
echo

curl -XPOST \
  -H "Authorization: Token token=$PD_AUTH_TOKEN" \
  -H "Accept: application/vnd.pagerduty+json;version=2" \
  -H "Content-Type: application/json" \
  --data "$pd_payload" \
  "https://events.pagerduty.com/v2/enqueue"
