#! /usr/bin/env bash

set -eu -o pipefail

#
# Deploy the orders migrations
#

usage() {
  echo "$0 <environment> [<circleci_sha1>]"
  exit 1
}

readonly environment="${1:-experimental}"
CIRCLE_SHA1="${2:-}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  experimental)
    compare_host=tsp.experimental.move.mil
    ;;
  staging)
    compare_host=tsp.staging.move.mil
    ;;
  prod)
    compare_host=tsp.move.mil
    ;;
  *)
    echo "<environment> must be one of experimental, staging, or prod"
    exit 1
    ;;
esac

if [ -z "${AWS_ACCOUNT_ID}" ]; then
  echo "AWS_ACCOUNT_ID not found!"
  echo "Please add 'AWS_ACCOUNT_ID' to your .envrc.local"
  exit 1
fi

APP_ENVIRONMENT="${environment}"
AWS_DEFAULT_REGION=us-west-2

if [ -z "${CIRCLE_SHA1}" ]; then
  KEY=$(chamber read app-experimental move_mil_dod_tls_key -q | base64 -i -)
  CERT=$(chamber read app-experimental move_mil_dod_tls_cert -q | base64 -i -)
  CA=$(chamber read app-experimental move_mil_dod_ca_cert -q | base64 -i -)

  CIRCLE_SHA1=$(curl -sk --key <(echo "${KEY}" | base64 --decode) --cert <(echo "${CERT}" | base64 --decode) --cacert <(echo "${CA}" | base64 --decode) "https://${compare_host}/health"  | jq -r .gitCommit)

  scripts/compare-deployed-commit "${compare_host}" "${CIRCLE_SHA1}"
fi

readonly image="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/orders-migrations:git-${CIRCLE_SHA1}"
scripts/ecs-run-orders-migrations-container "${image}" "${APP_ENVIRONMENT}"
