#! /usr/bin/env bash

set -eu -o pipefail

#
# Run health and TLS version checks
#

usage() {
  echo "$0 <environment>"
  exit 1
}

readonly environment="${1:-experimental}"

[[ -z "${environment}" ]] && usage

case "${environment}" in
  experimental)
    tls_health_check_hosts=tsp.experimental.move.mil
    ;;
  staging)
    tls_health_check_hosts=tsp.staging.move.mil
    ;;
  prod)
    tls_health_check_hosts=tsp.move.mil
    ;;
  *)
    echo "<environment> must be one of experimental, staging, or prod"
    exit 1
    ;;
esac

if [ -z "${AWS_ACCOUNT_ID}" ]; then
  echo "AWS_ACCOUNT_ID not found!"
  echo "Please add 'AWS_ACCOUNT_ID' to your .envrc.local"
  exit 1
fi

# Mutual TLS Hosts
KEY=$(chamber read app-experimental move_mil_dod_tls_key -q | base64 -i -)
CERT=$(chamber read app-experimental move_mil_dod_tls_cert -q | base64 -i -)
CA=$(chamber read app-experimental move_mil_dod_ca_cert -q | base64 -i -)

make bin/health-checker bin/tls-checker
bin/health-checker --schemes https --hosts "${tls_health_check_hosts}" --key "${KEY}" --cert "${CERT}" --ca "${CA}" --tries 10 --backoff 3 --log-level info --timeout 15m --verbose
bin/tls-checker    --schemes https --hosts "${tls_health_check_hosts}" --key "${KEY}" --cert "${CERT}" --ca "${CA}" --log-level info --timeout 15m --verbose
