#! /usr/bin/env bash

set -eu -o pipefail

UNAME_S=$(uname -s)
if [ "$UNAME_S" == "Linux" ]; then
  /usr/local/bin/swagger validate "/app/$1"
else
  docker run -v "${PWD}":/app milmove_orders_dev /usr/local/bin/swagger validate "/app/$1"
fi
