#! /usr/bin/env bash

set -eu -o pipefail

db_password="mysecretpassword"
db_port="${DB_PORT:-5432}"

command="${*:-}"

if [ -n "${command[*]}" ]; then
  exec /usr/bin/psql --variable "ON_ERROR_STOP=1" postgres://postgres:"${db_password}"@database:"${db_port}"/"${DB_NAME}" -c "${command}"
else
  exec /usr/bin/psql --variable "ON_ERROR_STOP=1" postgres://postgres:"${db_password}"@database:"${db_port}"/"${DB_NAME}"
fi
